version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REDIS_HOST=redis:6379
      - LIMITER=10
      - GIN_MODE=release
    depends_on: 
      - redis

  redis:
    image: "redis:alpine"